#include "DIO_Cfg.h"

const DIO_tstrPinCfg DIO_strPinCfg[32]=
{
	/*PORTA*//*pin direction*/ /* pull up pull Down*/
	/*PIN0*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN1*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN2*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN3*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN4*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN5*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN6*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN7*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	
	/*PORTB*//*pin direction*/ /* pull up pull Down*/
	/*PIN8*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN9*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN10*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN11*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN12*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN13*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN14*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN15*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	
	/*PORTC*//*pin direction*/ /* pull up pull Down*/
	/*PIN16*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN17*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN18*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN19*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN20*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN21*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN22*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN23*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	
	/*PORTD*//*pin direction*/ /* pull up pull Down*/
	/*PIN24*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN25*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN26*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN27*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN28*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN29*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN30*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN},
	/*PIN31*/{DIO_DIR_OUTPUT, DIO_INPUT_PULL_DOWN}
	
};
