/**********************DIO CONIFUGURATION FILE*********************/


#ifndef DIO_CFG_H
#define DIO_CFG_H

#include "../../LIB/STD_TYPES.h"

#define DIO_DIR_INPUT 	0
#define DIO_DIR_OUTPUT 	1

 
#define DIO_INPUT_PULL_UP 	0
#define DIO_INPUT_PULL_DOWN 	1


typedef struct {
	u8 DIO_PinDirection;
	u8 DIO_InputStatus;
}DIO_tstrPinCfg;




/*PORTA*/
#define DIO_PIN0_DIR	DIO_DIR_OUTPUT
#define DIO_PIN1_DIR	DIO_DIR_OUTPUT
#define DIO_PIN2_DIR	DIO_DIR_OUTPUT
#define DIO_PIN3_DIR	DIO_DIR_OUTPUT
#define DIO_PIN4_DIR	DIO_DIR_OUTPUT
#define DIO_PIN5_DIR	DIO_DIR_OUTPUT
#define DIO_PIN6_DIR	DIO_DIR_OUTPUT
#define DIO_PIN7_DIR	DIO_DIR_OUTPUT

/*PORTB*/
#define DIO_PIN8_DIR	DIO_DIR_OUTPUT
#define DIO_PIN9_DIR	DIO_DIR_OUTPUT
#define DIO_PIN10_DIR	DIO_DIR_OUTPUT
#define DIO_PIN11_DIR	DIO_DIR_OUTPUT
#define DIO_PIN12_DIR	DIO_DIR_OUTPUT
#define DIO_PIN13_DIR	DIO_DIR_OUTPUT
#define DIO_PIN14_DIR	DIO_DIR_OUTPUT
#define DIO_PIN15_DIR	DIO_DIR_OUTPUT

/*PORTC*/
#define DIO_PIN16_DIR	DIO_DIR_OUTPUT
#define DIO_PIN17_DIR	DIO_DIR_OUTPUT
#define DIO_PIN18_DIR	DIO_DIR_OUTPUT
#define DIO_PIN19_DIR	DIO_DIR_OUTPUT
#define DIO_PIN20_DIR	DIO_DIR_OUTPUT
#define DIO_PIN21_DIR	DIO_DIR_OUTPUT
#define DIO_PIN22_DIR	DIO_DIR_OUTPUT
#define DIO_PIN23_DIR	DIO_DIR_OUTPUT

/*PORTD*/
#define DIO_PIN24_DIR	DIO_DIR_OUTPUT
#define DIO_PIN25_DIR	DIO_DIR_OUTPUT
#define DIO_PIN26_DIR	DIO_DIR_OUTPUT
#define DIO_PIN27_DIR	DIO_DIR_OUTPUT
#define DIO_PIN28_DIR	DIO_DIR_OUTPUT
#define DIO_PIN29_DIR	DIO_DIR_OUTPUT
#define DIO_PIN30_DIR	DIO_DIR_OUTPUT
#define DIO_PIN31_DIR	DIO_DIR_OUTPUT

extern const DIO_tstrPinCfg DIO_strPinCfg[32];


#endif
