/*
 * EXTI_Cfg.h
 *
 * Created: 1/27/2023 10:11:25 AM
 *  Author: Sarah
 */ 


#ifndef EXTI_CFG_H_
#define EXTI_CFG_H_


#define INT0_MODE	INT0_MODE_RISING_EDGE
#define INT1_MODE	INT1_MODE_FALLING_EDGE
#define INT2_MODE	INT2_MODE_RISING_EDGE

#define INT0_MODE_FALLING_EDGE	0b10
#define INT0_MODE_RISING_EDGE	0b11
#define INT0_MODE_ON_CHANGE		0b01
#define INT0_MODE_LOW_LEVEL		0b00


#define INT1_MODE_FALLING_EDGE	0b10
#define INT1_MODE_RISING_EDGE	0b11
#define INT1_MODE_ON_CHANGE		0b01
#define INT1_MODE_LOW_LEVEL		0b00

#define INT2_MODE_FALLING_EDGE	0b0
#define INT2_MODE_RISING_EDGE	0b1

#endif /* EXTI_CFG_H_ */